select *
from customer_shopping
limit 10;


--Q1: Calculate the total Revenue Generated by Male vs Female Customers?

select gender,sum(purchase_amount) as revenue
from customer_shopping
group by gender


--Q2. WHich customer used discount but still purchased more than average price?
--Ideas-------------
--this is an trick question and the best qpproach to handle this
--knowing the avg purchase amount 
--discount applied yes or no, in this case yes
--combining them into this 
select customer_id, purchase_amount
from customer_shopping
where discount_applied = 'Yes' and 
purchase_amount >=(select Avg(purchase_amount) 

from customer_shopping);



--Q3. Top 5 products with the average highest review rating
Select item_purchased, round(Avg(review_rating::numeric),2) as "Average rating"
from customer_shopping 
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
limit 5;



--Q4. Compare the average purchase amount between express and standard shipping
select shipping_type,
round(avg(purchase_amount),2)
from customer_shopping
where shipping_type in ('Express', 'Standard')
group by shipping_type;


--q5: do subscribers spend more? 
--calculate the average amount spend and 
--total revenue between subscribers and non-subscribers?

select  subscription_status,
count(customer_id) as totalcustomers,
round(avg(purchase_amount), 2) as avgspend,
round(sum(purchase_amount), 2) as totalrevenue
from customer_shopping
group by subscription_status
order by totalrevenue, avgspend desc;

--q6: Which 5 products has the highest
--purchase with disocunt applied
select 
item_purchased,
Round(100*sum(CASE when discount_applied = 'Yes' then 1 Else 0 End)/count(*),2)
as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5; 

--Q7. Segment sustoemrs into New, Returning, and loyal based on 
--their total number of previous purchases and show teh count on each 
--segment. 
with customer_type as (
select customer_id, previous_purchases,
Case 
  When previous_purchases = 1 Then 'New'
  When previous_purchases between 2 and 10 Then 'Returning'
  Else 'Loyal' 
  End As customer_segment
From customer_shopping
)
Select customer_segment, count(*) As "Number of Customers"
from customer_type
group by customer_segment;



--q8.Top 3 most purchsed product in each category
with item_counts as (
Select category,
item_purchased,
Count(customer_id) as total_orders,
Row_Number()over(
  partition by category 
  order by count (customer_id)DESC) as item_rank
from customer_shopping
group by category,item_purchased
)
Select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;


--q9: Are customer who are repeat buyers(more than 5 purchases) also subscribes
SELECT subscription_status,
count(customer_id)as repeated_buyers
from customer_shopping
where purchase_amount > 5
group by subscription_status;


--q10: REvenue by each age group

SELECT age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping
GROUP BY age_group
ORDER BY total_revenue DESC;


